In [ ]:
li = []

li2 = ['a']

In [2]:
import re

text = "Congrats to our newest hire! #NurvaiResearcherOfTheWeek"

companies = ["Wexpand", "Nurvai", "WexpandTalent"]

# Extract hashtags without #
hashtags = re.findall(r"#(\w+)", text)

campaign_company = None

for tag in hashtags:
    for company in companies:
        if company.lower() in tag.lower():
            campaign_company = company
            campaign = tag
            break
    if campaign_company:
        break

print(campaign)  # Nurvai

NurvaiResearcherOfTheWeek

In [1]:
import os 

import pandas as pd
import numpy as np

from sqlalchemy import create_engine, text, String
from dotenv import load_dotenv
from utils import add_row_hash
from datetime import datetime

load_dotenv()

DATABASE_USER = os.getenv("DATABASE_USER")
DATABASE_PASSWORD = os.getenv("MYSQL_PASSWORD")

engine_old = create_engine(f'mysql+pymysql://{DATABASE_USER}:{DATABASE_PASSWORD}@localhost:3306/mkt')
engine_new = create_engine(f'mysql+pymysql://{DATABASE_USER}:{DATABASE_PASSWORD}@localhost:3306/Marketing')

Accounts = pd.read_sql('SELECT * FROM SocialMediaAccounts',engine_new)

Metrics_old = pd.read_sql('SELECT * FROM Metrics', engine_old)

map = {
        ('x','nvai'):Accounts.loc[Accounts['channel']=='X','id'].values[0], 
        ('lin','buis'):Accounts.loc[(Accounts['channel']=='LinkedIn') & (Accounts['brand_id'] == 2),'id'].values[0],
        ('lin','tal'):Accounts.loc[(Accounts['channel']=='LinkedIn') & (Accounts['brand_id'] == 3),'id'].values[0],
        ('lin','nvai'):Accounts.loc[(Accounts['channel']=='LinkedIn') & (Accounts['brand_id'] == 1),'id'].values[0],
        }

Metrics_old['account_id'] = [map[(chan,acc)] for chan, acc in zip(Metrics_old['chan'],Metrics_old['acc'])] 

Metrics_new = Metrics_old.drop(columns=['row_hash','updated_at','acc','chan','generalPageUniqueVisitors', 'generalPageViews','jobsPageUniqueVisitors', 'jobsPageViews', 
                                        'lifePageUniqueVisitors','lifePageViews', 'mediaViews', 'pageViews', 'pageViewsDesktop','pageViewsMobile', 'postsCreated', 'profileVisits', 
                                         'uniqueVisitors','uniqueVisitorsDesktop', 'uniqueVisitorsMobile', 'videoViews','timesSent'])

int_cols = ["bookmarks","clicks","comments","engagements","followersGained","followersTotal","impressions",
            "reactions", "shares", "unfollows", "account_id"]

for col in int_cols:
    print(col)
    Metrics_new[col] = (Metrics_new[col]//1).astype("Int64")


Metrics_new["row_hash"] = add_row_hash(Metrics_new[['date','account_id']])['row_hash']
Metrics_new['updated_at'] = datetime.now()

#Metrics_new.to_sql('Metrics',engine_new,if_exists='append',index=False)

Posts_old = pd.read_sql('SELECT * FROM Posts', engine_old)

bookmarks
clicks
comments
engagements
followersGained
followersTotal
impressions
reactions
shares
unfollows
account_id

In [58]:
Formats = pd.read_sql("SELECT * FROM Formats", engine_new, index_col='id')

In [43]:
col = "engagements"

s = Metrics_new[col]

bad_mask = (
    s.notna() &
    (s != s.astype(int))
)

print(Metrics_new.loc[bad_mask, [col]])

     engagements
7            1.0
12           7.0
34           6.0
100         15.0
124          2.0
133          1.0
163          4.0
223          7.0
226          4.0
284          3.0
287         37.0
288          7.0
342          2.0
394         14.0
407          7.0
443         32.0
451        100.0
631          1.0
655          6.0
667          7.0
785         30.0
806         11.0

In [57]:
Formats

    id                   format
0    5  Blog/Article/Newsletter
1    6                 Carousel
2   11               Case Study
3   10             Downloadable
4    4           Picture & Text
5    8                    Reply
6    2         Repost With Text
7    9         Short Video/Reel
8    3         Single Text Post
9    7                   Storie
10  13                   Survey
11  12                   Thread
12   1          Tweet (2 Lines)

In [61]:
Formats.to_dict()

{'format': {5: 'Blog/Article/Newsletter',
  6: 'Carousel',
  11: 'Case Study',
  10: 'Downloadable',
  4: 'Picture & Text',
  8: 'Reply',
  2: 'Repost With Text',
  9: 'Short Video/Reel',
  3: 'Single Text Post',
  7: 'Storie',
  13: 'Survey',
  12: 'Thread',
  1: 'Tweet (2 Lines)'}}

In [62]:
Formats = pd.read_sql("SELECT * FROM Formats", engine_new, index_col='id').to_dict()["format"]

In [63]:
Formats

{5: 'Blog/Article/Newsletter',
 6: 'Carousel',
 11: 'Case Study',
 10: 'Downloadable',
 4: 'Picture & Text',
 8: 'Reply',
 2: 'Repost With Text',
 9: 'Short Video/Reel',
 3: 'Single Text Post',
 7: 'Storie',
 13: 'Survey',
 12: 'Thread',
 1: 'Tweet (2 Lines)'}

In [64]:
CONTENT_PILLARS = pd.read_sql("SELECT * FROM ContentPillars", engine_new, index_col='id').to_dict()

In [65]:
CONTENT_PILLARS

{'pillar': {4: 'Creative/Inspiring',
  2: 'Educational',
  3: 'Promotional',
  1: 'Value'}}

In [67]:
all_strat_pillars = pd.read_sql("SELECT * FROM StrategyPillars", engine_new, index_col='id')

STRAT_PILLARS_NVAI = all_strat_pillars[all_strat_pillars['brand_id'] == 1].to_dict()['pillar']
STRAT_PILLARS_BUIS = all_strat_pillars[all_strat_pillars['brand_id'] == 2].to_dict()['pillar']
STRAT_PILLARS_TAL = all_strat_pillars[all_strat_pillars['brand_id'] == 3].to_dict()['pillar']

In [69]:
STRAT_PILLARS_BUIS

{17: 'Commercial Awareness',
 14: 'Compliance & Legal Expertise',
 13: 'Future Ready and High Performance Talent',
 15: 'HR Experience',
 16: 'Proof & Trust',
 12: 'Why Mexico'}

In [70]:
STRAT_PILLARS_NVAI

{6: 'Amplification of External Knowledge',
 5: 'Behind the Scenes',
 3: 'Data Insights',
 2: 'Main Issues/Stopers of data collection',
 1: 'Robotics News',
 4: 'Test/Research'}

In [71]:
STRAT_PILLARS_TAL

{8: 'Crecimiento & Academia',
 11: 'Global Exposure',
 10: 'Human Touch',
 7: 'Inside Wexpand (Vida y Cultura)',
 9: 'People-First & Wellness'}

In [72]:
Accounts

   id  brand_id    channel
0   2         1   LinkedIn
1   1         1          X
2   3         2   LinkedIn
3   5         3  Instagram
4   4         3   LinkedIn

In [3]:
import os 
import ollama
import json

import pandas as pd
import numpy as np

from sqlalchemy import create_engine
from sklearn.metrics.pairwise import cosine_similarity
from dotenv import load_dotenv
from utils import add_row_hash
from datetime import datetime



load_dotenv()

DATABASE_USER = os.getenv("DATABASE_USER")
DATABASE_PASSWORD = os.getenv("MYSQL_PASSWORD")

EMBED_MODEL = os.getenv("EMBED_MODEL")
LLM_MODEL = os.getenv("LLM_MODEL")

TOP_K = 5

def get_embedding(text):
    response = ollama.embeddings(
        model=EMBED_MODEL,
        prompt=text
    )
    return response["embedding"]

def retrieve_similar_posts(post_text, source, df, top_k=TOP_K):

    target_embedding = np.array(
        get_embedding(post_text)
    ).reshape(1, -1)

    source_df = df[df["account_id"] == source].copy()

    embeddings_matrix = np.vstack(source_df["embedding"].values)

    similarities = cosine_similarity(
        target_embedding,
        embeddings_matrix
    )[0]

    source_df["similarity"] = similarities

    source_df = source_df.sort_values(
        "similarity",
        ascending=False
    )

    # remove identical post
    source_df = source_df[
        source_df["postText"] != post_text
    ]

    return source_df.head(top_k)

def dict_to_prompt(title, d):
    rows = [f"{k} -> {v}" for k, v in d.items()]
    return f"{title}:\n" + "\n".join(rows)


def classify_post(
    post_text,
    source,
    df,
    formats,
    content_pillars,
    strategy_pillars
):

    similar_posts = retrieve_similar_posts(
        post_text,
        source,
        df
    )

    context_posts = "\n".join([
        f"- {t[:300]}"
        for t in similar_posts["postText"].tolist()
    ])

    prompt = f"""
You are a social media classifier.

Choose EXACTLY ONE ID from each category.

{dict_to_prompt("FORMATS", formats)}

{dict_to_prompt("CONTENT PILLARS", content_pillars)}

{dict_to_prompt("STRATEGY PILLARS", strategy_pillars)}

POST:
{post_text}

SIMILAR POSTS FROM SAME SOURCE:
{context_posts}

RULES:
- Return ONLY valid JSON
- Use ONLY integer IDs
- Do NOT explain
- Do NOT output markdown

OUTPUT FORMAT:
{{
    "format_id": 1,
    "content_pillar_id": 1,
    "strategy_pillar_id": 1
}}
"""

    response = ollama.chat(
        model=LLM_MODEL,
        messages=[
            {
                "role": "user",
                "content": prompt
            }
        ],
        options={
            "temperature": 0
        }
    )

    content = response["message"]["content"]

    try:
        return json.loads(content)

    except Exception:
        print(content)
        raise ValueError("Model returned invalid JSON")


engine_old = create_engine(f'mysql+pymysql://{DATABASE_USER}:{DATABASE_PASSWORD}@localhost:3306/mkt')
engine_new = create_engine(f'mysql+pymysql://{DATABASE_USER}:{DATABASE_PASSWORD}@localhost:3306/Marketing')

Accounts = pd.read_sql('SELECT * FROM SocialMediaAccounts',engine_new)

Metrics_old = pd.read_sql('SELECT * FROM Metrics', engine_old)

map = {
        ('x','nvai'):Accounts.loc[Accounts['channel']=='X','id'].values[0], 
        ('lin','buis'):Accounts.loc[(Accounts['channel']=='LinkedIn') & (Accounts['brand_id'] == 2),'id'].values[0],
        ('lin','tal'):Accounts.loc[(Accounts['channel']=='LinkedIn') & (Accounts['brand_id'] == 3),'id'].values[0],
        ('lin','nvai'):Accounts.loc[(Accounts['channel']=='LinkedIn') & (Accounts['brand_id'] == 1),'id'].values[0],
        }

Metrics_old['account_id'] = [map[(chan,acc)] for chan, acc in zip(Metrics_old['chan'],Metrics_old['acc'])] 

Metrics_new = Metrics_old.drop(columns=['row_hash','updated_at','acc','chan','generalPageUniqueVisitors', 'generalPageViews','jobsPageUniqueVisitors', 'jobsPageViews', 
                                        'lifePageUniqueVisitors','lifePageViews', 'mediaViews', 'pageViews', 'pageViewsDesktop','pageViewsMobile', 'postsCreated', 'profileVisits', 
                                         'uniqueVisitors','uniqueVisitorsDesktop', 'uniqueVisitorsMobile', 'videoViews','timesSent'])

int_cols = ["bookmarks","clicks","comments","engagements","followersGained","followersTotal","impressions",
            "reactions", "shares", "unfollows", "account_id"]

for col in int_cols:
    print(col)
    Metrics_new[col] = (Metrics_new[col]//1).astype("Int64")

Metrics_new["row_hash"] = add_row_hash(Metrics_new[['date','account_id']])['row_hash']
Metrics_new['updated_at'] = datetime.now()

#Metrics_new.to_sql('Metrics',engine_new,if_exists='append',index=False)

Posts_old = pd.read_sql("SELECT * FROM Posts",engine_old)

Posts_old['account_id'] = [map[(chan,acc)] for chan, acc in zip(Posts_old['chan'],Posts_old['acc'])] 

FORMATS = pd.read_sql("SELECT * FROM Formats", engine_new, index_col='id').to_dict()["format"]
CONTENT_PILLARS = pd.read_sql("SELECT * FROM ContentPillars", engine_new, index_col='id').to_dict()["pillar"]

all_strat_pillars = pd.read_sql("SELECT * FROM StrategyPillars", engine_new, index_col='id')

STRAT_PILLARS_NVAI = all_strat_pillars[all_strat_pillars['brand_id'] == 1].to_dict()['pillar']
STRAT_PILLARS_BUIS = all_strat_pillars[all_strat_pillars['brand_id'] == 2].to_dict()['pillar']
STRAT_PILLARS_TAL = all_strat_pillars[all_strat_pillars['brand_id'] == 3].to_dict()['pillar']

# =========================
# BUILD EMBEDDINGS
# =========================

Posts_old["embedding"] = Posts_old["postText"].fillna("").apply(get_embedding)

# =========================
# MAP ACCOUNT -> STRATEGY PILLARS
# =========================

strategy_map = {
    Accounts.loc[
        (Accounts["channel"] == "LinkedIn") &
        (Accounts["brand_id"] == 1),
        "id"
    ].values[0]: STRAT_PILLARS_NVAI,

    Accounts.loc[
        (Accounts["channel"] == "LinkedIn") &
        (Accounts["brand_id"] == 2),
        "id"
    ].values[0]: STRAT_PILLARS_BUIS,

    Accounts.loc[
        (Accounts["channel"] == "LinkedIn") &
        (Accounts["brand_id"] == 3),
        "id"
    ].values[0]: STRAT_PILLARS_TAL,

    Accounts.loc[
        Accounts["channel"] == "X",
        "id"
    ].values[0]: STRAT_PILLARS_NVAI
}

# =========================
# CLASSIFY POSTS
# =========================

results = []

for idx, row in Posts_old.iterrows():

    print(f"Classifying row {idx}")

    try:

        strategy_pillars = strategy_map[row["account_id"]]

        classification = classify_post(
            post_text=row["postText"],
            source=row["account_id"],
            df=Posts_old,
            formats=FORMATS,
            content_pillars=CONTENT_PILLARS,
            strategy_pillars=strategy_pillars
        )

        results.append(classification)

    except Exception as e:

        print(f"Failed on row {idx}: {e}")

        results.append({
            "format_id": pd.NA,
            "content_pillar_id": pd.NA,
            "strategy_pillar_id": pd.NA
        })

# =========================
# MERGE RESULTS
# =========================

classification_df = pd.DataFrame(results)

Posts_old["format_id"] = classification_df["format_id"]
Posts_old["content_pillar_id"] = classification_df["content_pillar_id"]
Posts_old["strategy_pillar_id"] = classification_df["strategy_pillar_id"]

bookmarks
clicks
comments
engagements
followersGained
followersTotal
impressions
reactions
shares
unfollows
account_id
Classifying row 0
Classifying row 1
Classifying row 2
Classifying row 3
Classifying row 4
Classifying row 5
Classifying row 6
Classifying row 7
Classifying row 8
Classifying row 9
Classifying row 10
Classifying row 11
Classifying row 12
Classifying row 13
Classifying row 14
Classifying row 15
Classifying row 16
Classifying row 17
Classifying row 18
Classifying row 19
Classifying row 20
Classifying row 21
Classifying row 22
Classifying row 23
Classifying row 24
Classifying row 25
Classifying row 26
Classifying row 27
Classifying row 28
Classifying row 29
Classifying row 30
Classifying row 31
Classifying row 32
Classifying row 33
Classifying row 34
Classifying row 35
Classifying row 36
Classifying row 37
Classifying row 38
Classifying row 39
Classifying row 40
Classifying row 41
Classifying row 42
Classifying row 43
Classifying row 44
Classifying row 45
Classifying row 46
Classifying row 47
Classifying row 48
Classifying row 49
Classifying row 50
Classifying row 51
Classifying row 52
Classifying row 53
Classifying row 54
Classifying row 55
Classifying row 56
Classifying row 57
Classifying row 58
Classifying row 59
Classifying row 60
Classifying row 61
Classifying row 62
Classifying row 63
Classifying row 64
Classifying row 65
Classifying row 66
Classifying row 67
Classifying row 68
Classifying row 69
Classifying row 70
Classifying row 71
Classifying row 72
Classifying row 73
Classifying row 74
Classifying row 75
Classifying row 76
Classifying row 77
Classifying row 78
Classifying row 79
Classifying row 80
Classifying row 81
Classifying row 82
Classifying row 83
Classifying row 84
Classifying row 85
Classifying row 86
Classifying row 87
Classifying row 88
Classifying row 89
Classifying row 90
Classifying row 91
Classifying row 92
Classifying row 93
Classifying row 94
Classifying row 95
Classifying row 96
Classifying row 97
Classifying row 98
Classifying row 99
Classifying row 100
Classifying row 101
Classifying row 102
Classifying row 103
Classifying row 104
Classifying row 105
Classifying row 106
Classifying row 107
Classifying row 108
Classifying row 109
Classifying row 110
Classifying row 111
Classifying row 112
Classifying row 113
Classifying row 114
Classifying row 115
Classifying row 116
Classifying row 117
Classifying row 118
Classifying row 119
Classifying row 120
Classifying row 121
Classifying row 122
Classifying row 123
Classifying row 124
Classifying row 125
Classifying row 126
Classifying row 127
Classifying row 128
Classifying row 129
Classifying row 130
Classifying row 131
Classifying row 132
Classifying row 133
Classifying row 134
Classifying row 135
Classifying row 136
Classifying row 137
Classifying row 138
Classifying row 139
Classifying row 140
Classifying row 141
Classifying row 142
Classifying row 143
Classifying row 144
Classifying row 145
Classifying row 146
Classifying row 147
Classifying row 148
Classifying row 149
Classifying row 150
Classifying row 151
Classifying row 152
Classifying row 153
Classifying row 154
Classifying row 155
Classifying row 156
Classifying row 157
Classifying row 158
Classifying row 159
Classifying row 160
Classifying row 161
Classifying row 162
Classifying row 163
Classifying row 164
Classifying row 165
Classifying row 166
Classifying row 167
Classifying row 168
Classifying row 169
Classifying row 170
Classifying row 171
Classifying row 172
Classifying row 173
Classifying row 174
Classifying row 175
Classifying row 176
Classifying row 177
Classifying row 178
Classifying row 179
Classifying row 180
Classifying row 181
Classifying row 182
Classifying row 183
Classifying row 184
Classifying row 185
Classifying row 186
Classifying row 187
Classifying row 188
Classifying row 189
Classifying row 190
Classifying row 191
Classifying row 192
Classifying row 193
Classifying row 194
Classifying row 195
Classifying row 196
Classifying row 197
Classifying row 198
Classifying row 199
Classifying row 200
Classifying row 201
Classifying row 202
Classifying row 203
Classifying row 204
Classifying row 205
Classifying row 206
Classifying row 207
Classifying row 208
Classifying row 209
Classifying row 210
Classifying row 211
Classifying row 212
Classifying row 213
Classifying row 214
Classifying row 215
Classifying row 216
Classifying row 217
Classifying row 218
Classifying row 219
Classifying row 220
Classifying row 221
Classifying row 222
Classifying row 223
Classifying row 224
Classifying row 225
Classifying row 226
Classifying row 227
Classifying row 228
Classifying row 229
Classifying row 230
Classifying row 231
Classifying row 232
Classifying row 233
Classifying row 234
Classifying row 235
Classifying row 236
Classifying row 237
Classifying row 238
Classifying row 239
Classifying row 240
Classifying row 241
Classifying row 242
Classifying row 243
Classifying row 244
Classifying row 245
Classifying row 246
Classifying row 247
Classifying row 248
Classifying row 249
Classifying row 250
Classifying row 251
Classifying row 252
Classifying row 253
Classifying row 254
Classifying row 255
Classifying row 256
Classifying row 257
Classifying row 258
Classifying row 259
Classifying row 260
Classifying row 261
Classifying row 262
Classifying row 263
Classifying row 264
Classifying row 265
Classifying row 266
Classifying row 267
Classifying row 268
Classifying row 269
Classifying row 270
Classifying row 271
Classifying row 272
Classifying row 273
Classifying row 274
Classifying row 275
Classifying row 276
Classifying row 277
Classifying row 278
Classifying row 279
Classifying row 280
Classifying row 281
Classifying row 282
Classifying row 283
Classifying row 284
Classifying row 285
Classifying row 286
Classifying row 287
Classifying row 288
Classifying row 289
Classifying row 290
Classifying row 291
Classifying row 292
Classifying row 293

In [4]:
Posts_old

,postText,postUrl,postType,campaignName,postedBy,date,campaignStartDate,campaignEndDate,audience,impressions,...,pillar,umap_x,umap_y,row_hash,updated_at,account_id,embedding,format_id,content_pillar_id,strategy_pillar_id
0,This week's #NurvaiPaperOfTheWeek got us think...,https://www.linkedin.com/feed/update/urn:li:ac...,Orgánico,None,Mateo Yáñez Tanaka,2026-03-26,None,None,Todos los seguidores,61,...,ExtAmp,18.8905,9.31534,593bc9e0f1dd228c30af2ac3a5ce63ec,2026-04-06 08:19:40,2,"[-0.27665624022483826, 1.5198724269866943, -3....",3,2,2
1,This week as the Nurvai Paper of The Week we r...,https://www.linkedin.com/feed/update/urn:li:ac...,Orgánico,None,Andrea Palacios Ilizaliturri,2026-03-25,None,None,Todos los seguidores,186,...,ExtAmp,19.1267,8.99515,f5080f3bd579a23e455e9b481c6699fe,2026-04-06 08:19:40,2,"[0.7492364048957825, 1.7510989904403687, -3.99...",3,2,5
2,For this week's Nurvai Researcher of The Week ...,https://www.linkedin.com/feed/update/urn:li:ac...,Orgánico,None,Mateo Yáñez Tanaka,2026-03-24,None,None,Todos los seguidores,108,...,ExtAmp,18.8038,12.19500,0ebf8a6352c43e6fb1f67760be5f5efe,2026-04-06 08:19:40,2,"[0.011316861025989056, 2.2141807079315186, -3....",3,2,3
3,This week's #NurvaiPaperOfTheWeek got us think...,https://www.linkedin.com/feed/update/urn:li:ac...,Orgánico,None,Mateo Yáñez Tanaka,2026-03-19,None,None,Todos los seguidores,121,...,ExtAmp,16.5955,11.28620,4ec157a8871fd6900038e4e3ec5b3ed6,2026-04-06 08:19:40,2,"[-0.16267332434654236, 2.0487265586853027, -3....",3,2,2
4,This week as the Nurvai Paper of The Week we r...,https://www.linkedin.com/feed/update/urn:li:ac...,Orgánico,None,Andrea Palacios Ilizaliturri,2026-03-18,None,None,Todos los seguidores,265,...,ExtAmp,19.1565,10.30430,593ff221567fa13052ed04aeec6e8e7f,2026-04-06 08:19:40,2,"[-0.11181965470314026, 2.1225569248199463, -3....",3,4,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
289,"To address this, SeedPolicy introduces a self-...",https://x.com/nurvai_ai/status/203940728659918...,None,None,None,2026-04-01,None,None,None,7,...,ExtAmp,19.5583,11.69830,c36d6a8d69faf57da9cf9e2bbdc7fbb9,2026-04-06 08:19:40,1,"[0.6719858050346375, 0.6001504063606262, -2.72...",3,2,3
290,Simply increasing the observation window isn't...,https://x.com/nurvai_ai/status/203940728566802...,None,None,None,2026-04-01,None,None,None,5,...,ExtAmp,19.4557,11.55250,f64edbbec8025c2ff2c1d7bb0a6464de,2026-04-06 08:19:40,1,"[0.024355417117476463, 1.700285792350769, -2.8...",3,2,3
291,Diffusion policies work well for short-horizon...,https://x.com/nurvai_ai/status/203940728463209...,None,None,None,2026-04-01,None,None,None,17,...,ExtAmp,19.8036,11.66330,f42825c7f80b3cd783aa6cac9332cafe,2026-04-06 08:19:40,1,"[0.863499104976654, 1.5956276655197144, -3.210...",3,2,3
292,TL; DR Diffusion policies struggle with long-h...,https://x.com/nurvai_ai/status/203940728367578...,None,None,None,2026-04-01,None,None,None,10,...,ExtAmp,19.8269,11.75380,b5919ee3672d1ce516a3e8614ec815bc,2026-04-06 08:19:40,1,"[0.28753462433815, 1.1879006624221802, -3.5754...",3,2,5
293,For this week's #NurvaiPaperOfTheWeek we read ...,https://x.com/nurvai_ai/status/203940728204420...,None,None,None,2026-04-01,None,None,None,54,...,ExtAmp,19.8496,11.62350,3bece336a17a231632548a8c181e9cf3,2026-04-06 08:19:40,1,"[0.35524293780326843, -0.33917689323425293, -3...",4,2,3

In [7]:
Posts_old['format_id'].unique()

array([3, 2, 4])

In [8]:
FORMATS

{5: 'Blog/Article/Newsletter',
 6: 'Carousel',
 11: 'Case Study',
 10: 'Downloadable',
 4: 'Picture & Text',
 8: 'Reply',
 2: 'Repost With Text',
 9: 'Short Video/Reel',
 3: 'Single Text Post',
 7: 'Storie',
 13: 'Survey',
 12: 'Thread',
 1: 'Tweet (2 Lines)'}

In [9]:
CONTENT_PILLARS

{4: 'Creative/Inspiring', 2: 'Educational', 3: 'Promotional', 1: 'Value'}

In [10]:
STRAT_PILLARS_NVAI

{6: 'Amplification of External Knowledge',
 5: 'Behind the Scenes',
 3: 'Data Insights',
 2: 'Main Issues/Stopers of data collection',
 1: 'Robotics News',
 4: 'Test/Research'}

In [11]:
Posts_old

,postText,postUrl,postType,campaignName,postedBy,date,campaignStartDate,campaignEndDate,audience,impressions,...,pillar,umap_x,umap_y,row_hash,updated_at,account_id,embedding,format_id,content_pillar_id,strategy_pillar_id
0,This week's #NurvaiPaperOfTheWeek got us think...,https://www.linkedin.com/feed/update/urn:li:ac...,Orgánico,None,Mateo Yáñez Tanaka,2026-03-26,None,None,Todos los seguidores,61,...,ExtAmp,18.8905,9.31534,593bc9e0f1dd228c30af2ac3a5ce63ec,2026-04-06 08:19:40,2,"[-0.27665624022483826, 1.5198724269866943, -3....",3,2,2
1,This week as the Nurvai Paper of The Week we r...,https://www.linkedin.com/feed/update/urn:li:ac...,Orgánico,None,Andrea Palacios Ilizaliturri,2026-03-25,None,None,Todos los seguidores,186,...,ExtAmp,19.1267,8.99515,f5080f3bd579a23e455e9b481c6699fe,2026-04-06 08:19:40,2,"[0.7492364048957825, 1.7510989904403687, -3.99...",3,2,5
2,For this week's Nurvai Researcher of The Week ...,https://www.linkedin.com/feed/update/urn:li:ac...,Orgánico,None,Mateo Yáñez Tanaka,2026-03-24,None,None,Todos los seguidores,108,...,ExtAmp,18.8038,12.19500,0ebf8a6352c43e6fb1f67760be5f5efe,2026-04-06 08:19:40,2,"[0.011316861025989056, 2.2141807079315186, -3....",3,2,3
3,This week's #NurvaiPaperOfTheWeek got us think...,https://www.linkedin.com/feed/update/urn:li:ac...,Orgánico,None,Mateo Yáñez Tanaka,2026-03-19,None,None,Todos los seguidores,121,...,ExtAmp,16.5955,11.28620,4ec157a8871fd6900038e4e3ec5b3ed6,2026-04-06 08:19:40,2,"[-0.16267332434654236, 2.0487265586853027, -3....",3,2,2
4,This week as the Nurvai Paper of The Week we r...,https://www.linkedin.com/feed/update/urn:li:ac...,Orgánico,None,Andrea Palacios Ilizaliturri,2026-03-18,None,None,Todos los seguidores,265,...,ExtAmp,19.1565,10.30430,593ff221567fa13052ed04aeec6e8e7f,2026-04-06 08:19:40,2,"[-0.11181965470314026, 2.1225569248199463, -3....",3,4,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
289,"To address this, SeedPolicy introduces a self-...",https://x.com/nurvai_ai/status/203940728659918...,None,None,None,2026-04-01,None,None,None,7,...,ExtAmp,19.5583,11.69830,c36d6a8d69faf57da9cf9e2bbdc7fbb9,2026-04-06 08:19:40,1,"[0.6719858050346375, 0.6001504063606262, -2.72...",3,2,3
290,Simply increasing the observation window isn't...,https://x.com/nurvai_ai/status/203940728566802...,None,None,None,2026-04-01,None,None,None,5,...,ExtAmp,19.4557,11.55250,f64edbbec8025c2ff2c1d7bb0a6464de,2026-04-06 08:19:40,1,"[0.024355417117476463, 1.700285792350769, -2.8...",3,2,3
291,Diffusion policies work well for short-horizon...,https://x.com/nurvai_ai/status/203940728463209...,None,None,None,2026-04-01,None,None,None,17,...,ExtAmp,19.8036,11.66330,f42825c7f80b3cd783aa6cac9332cafe,2026-04-06 08:19:40,1,"[0.863499104976654, 1.5956276655197144, -3.210...",3,2,3
292,TL; DR Diffusion policies struggle with long-h...,https://x.com/nurvai_ai/status/203940728367578...,None,None,None,2026-04-01,None,None,None,10,...,ExtAmp,19.8269,11.75380,b5919ee3672d1ce516a3e8614ec815bc,2026-04-06 08:19:40,1,"[0.28753462433815, 1.1879006624221802, -3.5754...",3,2,5
293,For this week's #NurvaiPaperOfTheWeek we read ...,https://x.com/nurvai_ai/status/203940728204420...,None,None,None,2026-04-01,None,None,None,54,...,ExtAmp,19.8496,11.62350,3bece336a17a231632548a8c181e9cf3,2026-04-06 08:19:40,1,"[0.35524293780326843, -0.33917689323425293, -3...",4,2,3

In [3]:
engine_old = create_engine(f'mysql+pymysql://{DATABASE_USER}:{DATABASE_PASSWORD}@localhost:3306/mkt')
engine_new = create_engine(f'mysql+pymysql://{DATABASE_USER}:{DATABASE_PASSWORD}@localhost:3306/Marketing')

Accounts = pd.read_sql('SELECT * FROM SocialMediaAccounts',engine_new)

Metrics_old = pd.read_sql('SELECT * FROM Metrics', engine_old)

map = {
        ('x','nvai'):Accounts.loc[Accounts['channel']=='X','id'].values[0], 
        ('lin','buis'):Accounts.loc[(Accounts['channel']=='LinkedIn') & (Accounts['brand_id'] == 2),'id'].values[0],
        ('lin','tal'):Accounts.loc[(Accounts['channel']=='LinkedIn') & (Accounts['brand_id'] == 3),'id'].values[0],
        ('lin','nvai'):Accounts.loc[(Accounts['channel']=='LinkedIn') & (Accounts['brand_id'] == 1),'id'].values[0],
        }

Metrics_old['account_id'] = [map[(chan,acc)] for chan, acc in zip(Metrics_old['chan'],Metrics_old['acc'])] 

metrics_new_columns = list(pd.read_sql('SELECT * FROM Metrics',engine_new).drop(columns = ['row_hash','updated_at']).columns)

Metrics_new = Metrics_old[metrics_new_columns]

int_cols = ["bookmarks","clicks","comments","engagements","followersGained","followersTotal","impressions",
            "reactions", "shares", "unfollows", "account_id"]

for col in int_cols:
    Metrics_new[col] = (Metrics_new[col]//1).astype("Int64")

Metrics_new["row_hash"] = add_row_hash(Metrics_new[['date','account_id']])['row_hash']
Metrics_new['updated_at'] = datetime.now()

/var/folders/r4/cgt8yk6940sc706r8hzzvkkr0000gn/T/ipykernel_45460/3134089941.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Metrics_new[col] = (Metrics_new[col]//1).astype("Int64")
/var/folders/r4/cgt8yk6940sc706r8hzzvkkr0000gn/T/ipykernel_45460/3134089941.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Metrics_new[col] = (Metrics_new[col]//1).astype("Int64")
/var/folders/r4/cgt8yk6940sc706r8hzzvkkr0000gn/T/ipykernel_45460/3134089941.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Metrics_new[col] = (Metrics_new[col]//1).astype("Int64")
/var/folders/r4/cgt8yk6940sc706r8hzzvkkr0000gn/T/ipykernel_45460/3134089941.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Metrics_new[col] = (Metrics_new[col]//1).astype("Int64")
/var/folders/r4/cgt8yk6940sc706r8hzzvkkr0000gn/T/ipykernel_45460/3134089941.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Metrics_new[col] = (Metrics_new[col]//1).astype("Int64")
/var/folders/r4/cgt8yk6940sc706r8hzzvkkr0000gn/T/ipykernel_45460/3134089941.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Metrics_new[col] = (Metrics_new[col]//1).astype("Int64")
/var/folders/r4/cgt8yk6940sc706r8hzzvkkr0000gn/T/ipykernel_45460/3134089941.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Metrics_new[col] = (Metrics_new[col]//1).astype("Int64")
/var/folders/r4/cgt8yk6940sc706r8hzzvkkr0000gn/T/ipykernel_45460/3134089941.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Metrics_new[col] = (Metrics_new[col]//1).astype("Int64")
/var/folders/r4/cgt8yk6940sc706r8hzzvkkr0000gn/T/ipykernel_45460/3134089941.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Metrics_new[col] = (Metrics_new[col]//1).astype("Int64")
/var/folders/r4/cgt8yk6940sc706r8hzzvkkr0000gn/T/ipykernel_45460/3134089941.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Metrics_new[col] = (Metrics_new[col]//1).astype("Int64")
/var/folders/r4/cgt8yk6940sc706r8hzzvkkr0000gn/T/ipykernel_45460/3134089941.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Metrics_new[col] = (Metrics_new[col]//1).astype("Int64")
/var/folders/r4/cgt8yk6940sc706r8hzzvkkr0000gn/T/ipykernel_45460/3134089941.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Metrics_new["row_hash"] = add_row_hash(Metrics_new[['date','account_id']])['row_hash']
/var/folders/r4/cgt8yk6940sc706r8hzzvkkr0000gn/T/ipykernel_45460/3134089941.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Metrics_new['updated_at'] = datetime.now()

In [4]:
Metrics_new

,account_id,bookmarks,clicks,comments,date,engagementRate,engagements,followersGained,followersTotal,impressions,reactions,shares,unfollows,row_hash,updated_at
0,3,<NA>,0,0,2026-01-01,0.000000,0,0,869,18,0,0,<NA>,cb8aa796c69bbe53558c8f5a29a8b108,2026-05-15 09:11:20.930683
1,3,<NA>,0,0,2026-01-02,0.000000,0,2,871,75,0,0,<NA>,de905b6c80c10db5ccffdd3881d89071,2026-05-15 09:11:20.930683
2,3,<NA>,0,0,2026-01-03,0.000000,0,1,872,9,0,0,<NA>,ea37a4957a6be1f6f8717c746065c4c4,2026-05-15 09:11:20.930683
3,3,<NA>,0,0,2026-01-04,0.000000,0,0,872,49,0,0,<NA>,46f158a3a3e003fb4037898f9b4f9add,2026-05-15 09:11:20.930683
4,3,<NA>,0,0,2026-01-05,0.000000,0,2,874,88,0,0,<NA>,1a6d718ccf1c3d0945fd880095afd86e,2026-05-15 09:11:20.930683
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1517,1,1,<NA>,2,2026-04-02,0.017683,29,2,89,1640,4,1,0,3bc7298cb509de57d8a504bdddaa08f7,2026-05-15 09:11:20.930683
1518,1,1,<NA>,0,2026-04-03,0.002339,2,0,89,855,0,0,0,6356270ae4e380d41f3f1773b6d0b4fd,2026-05-15 09:11:20.930683
1519,1,0,<NA>,0,2026-04-04,0.024845,4,1,89,161,0,0,1,ed976146dcb3ecdeff5bf36a39897709,2026-05-15 09:11:20.930683
1520,1,0,<NA>,0,2026-04-06,0.000000,0,0,89,74,0,0,0,91b0ac414ea6b61e7941730f4270cdd8,2026-05-15 09:11:20.930683
1521,1,0,<NA>,0,2026-04-05,0.009524,1,0,89,105,0,0,0,679c75ff092f43393f55301397545fa4,2026-05-15 09:11:20.930683

In [14]:
Posts_old['created_at'] = Posts_old['date']
posts_new_columns = list(pd.read_sql('SELECT * FROM Posts',engine_new).drop(columns = ['row_hash','updated_at']).columns)

Posts_new = Posts_old[posts_new_columns]

for col in int_cols:
    if col in Posts_new.columns:
        Posts_new[col] = (Posts_new[col]//1).astype("Int64")
        
Posts_new["row_hash"] = add_row_hash(Posts_new[['postText','account_id']])['row_hash']
Posts_new['updated_at'] = datetime.now()

/var/folders/r4/cgt8yk6940sc706r8hzzvkkr0000gn/T/ipykernel_2008/1041475189.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Posts_new[col] = (Posts_new[col]//1).astype("Int64")
/var/folders/r4/cgt8yk6940sc706r8hzzvkkr0000gn/T/ipykernel_2008/1041475189.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Posts_new[col] = (Posts_new[col]//1).astype("Int64")
/var/folders/r4/cgt8yk6940sc706r8hzzvkkr0000gn/T/ipykernel_2008/1041475189.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Posts_new[col] = (Posts_new[col]//1).astype("Int64")
/var/folders/r4/cgt8yk6940sc706r8hzzvkkr0000gn/T/ipykernel_2008/1041475189.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Posts_new[col] = (Posts_new[col]//1).astype("Int64")
/var/folders/r4/cgt8yk6940sc706r8hzzvkkr0000gn/T/ipykernel_2008/1041475189.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Posts_new[col] = (Posts_new[col]//1).astype("Int64")
/var/folders/r4/cgt8yk6940sc706r8hzzvkkr0000gn/T/ipykernel_2008/1041475189.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Posts_new[col] = (Posts_new[col]//1).astype("Int64")
/var/folders/r4/cgt8yk6940sc706r8hzzvkkr0000gn/T/ipykernel_2008/1041475189.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Posts_new[col] = (Posts_new[col]//1).astype("Int64")
/var/folders/r4/cgt8yk6940sc706r8hzzvkkr0000gn/T/ipykernel_2008/1041475189.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Posts_new[col] = (Posts_new[col]//1).astype("Int64")
/var/folders/r4/cgt8yk6940sc706r8hzzvkkr0000gn/T/ipykernel_2008/1041475189.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Posts_new[col] = (Posts_new[col]//1).astype("Int64")
/var/folders/r4/cgt8yk6940sc706r8hzzvkkr0000gn/T/ipykernel_2008/1041475189.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Posts_new["row_hash"] = add_row_hash(Posts_new[['postText','account_id']])['row_hash']
/var/folders/r4/cgt8yk6940sc706r8hzzvkkr0000gn/T/ipykernel_2008/1041475189.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Posts_new['updated_at'] = datetime.now()

In [17]:
Posts_new.columns

Index(['postText', 'postUrl', 'format_id', 'content_pillar_id',
       'strategy_pillar_id', 'created_at', 'impressions', 'views', 'clicks',
       'clickThroughRate', 'reactions', 'comments', 'shares',
       'followersGained', 'engagementRate', 'engagements', 'bookmarks',
       'timesSent', 'profileVisits', 'detailExpands', 'urlClicks',
       'hashtagClicks', 'permalinkClicks', 'account_id', 'umap_x', 'umap_y',
       'row_hash', 'updated_at'],
      dtype='object')

In [18]:
posts_new_columns

['postText',
 'postUrl',
 'format_id',
 'content_pillar_id',
 'strategy_pillar_id',
 'created_at',
 'impressions',
 'views',
 'clicks',
 'clickThroughRate',
 'reactions',
 'comments',
 'shares',
 'followersGained',
 'engagementRate',
 'engagements',
 'bookmarks',
 'timesSent',
 'profileVisits',
 'detailExpands',
 'urlClicks',
 'hashtagClicks',
 'permalinkClicks',
 'account_id',
 'umap_x',
 'umap_y']